baseurl = "https://thomaswestland.github.io"
copyright = "Tom Westland and Emiliano Travieso are PhD students in economic history at the University of Cambridge."
disqusShortname = "shortname"
googleAnalytics = "trackingcode"
languageCode = "en"
theme = "Hucore"
title = "Decompressing | History"
[params]
author = "Morten G. Johansen"
description = "Your description here"
displayauthor = true
keywords = ["keyword 1", "keyword 2", "keyword 3"]
sharingicons = true
[params.highlight]
languages = ["go", "dockerfile"]
style = "github"
[[params.social]]
fa_icon = "fa-github"
url = "https://github.com/mgjohansen"
[[params.social]]
fa_icon = "fa-gitlab"
url = "https://gitlab.com/mgjohansen"
[[params.social]]
fa_icon = "fa-twitter"
url = "https://twitter.com/mgjohansen"
[[params.social]]
fa_icon = "fa-linkedin-square"
url = "https://linkedin.com/in/mgjohansen"
[[params.social]]
fa_icon = "fa-rss"
url = "/index.xml"
[[params.socialshare]]
fa_icon = "fa-linkedin-square"
url = "https://linkedin.com/in/mgjohansen"
[taxonomies]
category = "categories"
tag = "tags"
